# Generated by Django 4.1.7 on 2023-02-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='picture',
            field=models.ImageField(default='', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='storeowner',
            name='picture',
            field=models.ImageField(default='', upload_to='media'),
        ),
    ]
