# Generated by Django 4.1.7 on 2023-02-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0003_alter_costumer_picture_alter_item_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='picture',
            field=models.ImageField(default='', upload_to='static/static'),
        ),
        migrations.AlterField(
            model_name='costumer',
            name='picture',
            field=models.ImageField(default='', upload_to='static/static'),
        ),
        migrations.AlterField(
            model_name='item',
            name='picture',
            field=models.ImageField(default='', upload_to='static/static'),
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='picture',
            field=models.ImageField(default='', upload_to='static/static'),
        ),
        migrations.AlterField(
            model_name='storecategory',
            name='picture',
            field=models.ImageField(default='', upload_to='static/static'),
        ),
        migrations.AlterField(
            model_name='storeowner',
            name='picture',
            field=models.ImageField(default='', upload_to='static/static'),
        ),
    ]
