# Generated by Django 4.1.7 on 2023-02-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0004_store_picture_alter_costumer_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='picture',
            field=models.ImageField(default='', upload_to='static'),
        ),
        migrations.AlterField(
            model_name='item',
            name='picture',
            field=models.ImageField(default='', upload_to='static'),
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='picture',
            field=models.ImageField(default='', upload_to='static'),
        ),
        migrations.AlterField(
            model_name='store',
            name='picture',
            field=models.ImageField(default='', upload_to='static'),
        ),
        migrations.AlterField(
            model_name='storecategory',
            name='picture',
            field=models.ImageField(default='', upload_to='static'),
        ),
        migrations.AlterField(
            model_name='storeowner',
            name='picture',
            field=models.ImageField(default='', upload_to='static'),
        ),
    ]
